# Site settings
title: Adam's blog
email: adsteph@microsoft.com
description: > # The blog of Adam Stephensen
url: "https://adamstephensen.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate_path: "/blog/page:num/"
paginate: 10

# disqus: "YOUR DISCUSS KEY"
# google_analytics: "YOUR GOOGLE ANALYTICS KEY"
github_username:  adamstephensen

excerpt_length: 250

exclude:
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "package.json"
  - "Rakefile"
  - "Readme.md"
  - "LICENSE.txt"
  - "ignore"

include:
  - .nojekyll
  - robots.txt


gems:
  - jekyll-redirect-from
  - jekyll-categories
  - jekyll-paginate
  - bootstrap
  #- jekyll-bootstrap-sass

sass:
  style: compact # possible values: nested expanded compact compressed
  #sass_dir: _lib